apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tt79bc1jo-nodejs
  janus-idp.io/tekton: tt79bc1jo-nodejs
  backstage.io/kubernetes-id: tt79bc1jo-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tt79bc1jo-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
