apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tt79bc1jo-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tt79bc1jo-nodejs 
  name: tt79bc1jo-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: tt79bc1jo-nodejs 
